'use client';
import { ArrowDownToLine, ArrowUpFromLine, Banknote, CreditCard, LockKeyhole, Wallet } from 'lucide-react';
import * as React from 'react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/shared/page-header';
import { useSessionUser } from '@/components/providers/session-provider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input, Textarea } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { PERMISSIONS } from '@/constants/permissions';
import { apiGet, apiPost, ApiRequestError } from '@/lib/api/client';
import { formatMoney } from '@/lib/money';
interface Register{_id:string;status:string;openedAt:string;closedAt?:string;openingCashMinor:number;expectedCashMinor:number;closingCashActualMinor?:number;cashDifferenceMinor?:number;cashSalesMinor:number;cardSalesMinor:number;digitalWalletSalesMinor:number;refundsMinor:number;paidInMinor:number;paidOutMinor:number;cashierId?:{name:string};cashMovements:Array<{type:string;amountMinor:number;reason:string;createdAt:string}>} interface Data{current:Register|null;history:Register[]}
export function RegisterClient(){
 const user=useSessionUser(),canOpen=user.permissions.includes(PERMISSIONS.REGISTER_OPEN),canClose=user.permissions.includes(PERMISSIONS.REGISTER_CLOSE);const[data,setData]=React.useState<Data|null>(null),[dialog,setDialog]=React.useState<'open'|'movement'|'close'|null>(null),[saving,setSaving]=React.useState(false),[form,setForm]=React.useState({amount:'',type:'paid_in',reason:'',notes:''});const load=React.useCallback(async()=>setData(await apiGet<Data>('/api/register')),[]);React.useEffect(()=>{void load()},[load]);
 async function submit(){setSaving(true);try{const amountMinor=Math.round(Number(form.amount)*100);if(dialog==='open')await apiPost('/api/register',{openingCashMinor:amountMinor});else if(dialog==='movement'&&data?.current)await apiPost(`/api/register/${data.current._id}/movements`,{type:form.type,amountMinor,reason:form.reason});else if(dialog==='close'&&data?.current)await apiPost(`/api/register/${data.current._id}/close`,{closingCashActualMinor:amountMinor,closingNotes:form.notes});setDialog(null);setForm({amount:'',type:'paid_in',reason:'',notes:''});await load();toast.success(dialog==='close'?'Register closed':dialog==='open'?'Register opened':'Cash movement recorded')}catch(e){toast.error(e instanceof ApiRequestError?e.message:'Could not update the register.')}finally{setSaving(false)}}
 const r=data?.current;
 return <div className="space-y-5"><PageHeader description="Open and close cashier shifts, control the cash drawer, and review variances." actions={!r&&canOpen?<Button onClick={()=>setDialog('open')}><Wallet className="size-4"/>Open register</Button>:r?<><Button variant="outline" onClick={()=>setDialog('movement')}><ArrowDownToLine className="size-4"/>Cash movement</Button>{canClose&&<Button onClick={()=>setDialog('close')}><LockKeyhole className="size-4"/>Close register</Button>}</>:undefined}/>
  {r?<><Card className="overflow-hidden"><div className="flex flex-col gap-3 bg-primary px-5 py-4 text-primary-foreground sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Badge className="bg-white/20 text-white">Open shift</Badge><span className="text-xs opacity-80">Since {new Date(r.openedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div><h3 className="mt-2 text-xl font-semibold">{r.cashierId?.name??user.name}&apos;s register</h3></div><div className="text-left sm:text-right"><p className="text-xs opacity-75">Expected cash</p><p className="text-3xl font-semibold">{formatMoney(r.expectedCashMinor)}</p></div></div></Card>
   <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><M icon={Banknote} l="Cash sales" v={formatMoney(r.cashSalesMinor)}/><M icon={CreditCard} l="Card & wallet" v={formatMoney(r.cardSalesMinor+r.digitalWalletSalesMinor)}/><M icon={ArrowDownToLine} l="Paid in" v={formatMoney(r.paidInMinor)}/><M icon={ArrowUpFromLine} l="Paid out & refunds" v={formatMoney(r.paidOutMinor+r.refundsMinor)}/></div>
   <Card><CardHeader><CardTitle>Drawer movements</CardTitle></CardHeader><CardContent>{r.cashMovements.length?<div className="divide-y">{[...r.cashMovements].reverse().map((m,i)=><div className="flex items-center gap-3 py-3" key={`${m.createdAt}-${i}`}><div className={`rounded-lg p-2 ${m.type==='paid_in'?'bg-success/10 text-success':'bg-warning/10 text-warning'}`}>{m.type==='paid_in'?<ArrowDownToLine className="size-4"/>:<ArrowUpFromLine className="size-4"/>}</div><div className="flex-1"><p className="text-sm font-medium">{m.reason}</p><p className="text-xs text-muted-foreground">{new Date(m.createdAt).toLocaleString()}</p></div><p className="font-semibold">{m.type==='paid_in'?'+':'-'}{formatMoney(m.amountMinor)}</p></div>)}</div>:<p className="py-8 text-center text-sm text-muted-foreground">No manual cash movements in this shift.</p>}</CardContent></Card>
  </>:<Card><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><div className="rounded-2xl bg-muted p-4"><LockKeyhole className="size-7 text-muted-foreground"/></div><h3 className="mt-4 font-semibold">No register is open</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">Enter the counted opening float before taking cash payments for this shift.</p>{canOpen&&<Button className="mt-4" onClick={()=>setDialog('open')}>Open a register</Button>}</CardContent></Card>}
  {data?.history.length?<Card><CardHeader><CardTitle>Recent closed shifts</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/45 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">Cashier</th><th className="px-4 py-3">Opened</th><th className="px-4 py-3">Expected</th><th className="px-4 py-3">Counted</th><th className="px-4 py-3">Variance</th></tr></thead><tbody>{data.history.map(h=><tr className="border-t" key={h._id}><td className="px-4 py-3 font-medium">{h.cashierId?.name??'Cashier'}</td><td className="px-4 py-3">{new Date(h.openedAt).toLocaleDateString()}</td><td className="px-4 py-3">{formatMoney(h.expectedCashMinor)}</td><td className="px-4 py-3">{formatMoney(h.closingCashActualMinor??0)}</td><td className={`px-4 py-3 font-semibold ${(h.cashDifferenceMinor??0)<0?'text-destructive':'text-success'}`}>{formatMoney(h.cashDifferenceMinor??0)}</td></tr>)}</tbody></table></div></CardContent></Card>:null}
  <Dialog open={dialog!==null} onOpenChange={o=>!o&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog==='open'?'Open cash register':dialog==='close'?'Close and reconcile':'Record cash movement'}</DialogTitle></DialogHeader>{dialog==='movement'&&<F l="Movement"><Select value={form.type} onValueChange={v=>setForm({...form,type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="paid_in">Paid in</SelectItem><SelectItem value="paid_out">Paid out</SelectItem></SelectContent></Select></F>}<F l={dialog==='open'?'Opening cash':dialog==='close'?'Actual cash counted':'Amount'}><Input type="number" min="0" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></F>{dialog==='movement'&&<F l="Reason"><Input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></F>}{dialog==='close'&&<F l="Closing notes"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F>}<DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>Cancel</Button><Button loading={saving} disabled={form.amount===''||(dialog==='movement'&&!form.reason)} onClick={()=>void submit()}>{dialog==='close'?'Close register':'Confirm'}</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
function M({icon:Icon,l,v}:{icon:typeof Wallet;l:string;v:string}){return <Card><CardContent className="flex items-center justify-between p-4"><div><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-xl font-semibold">{v}</p></div><Icon className="size-5 text-primary"/></CardContent></Card>}function F({l,children}:{l:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{l}</Label>{children}</div>}
