'use client';
import { CheckCircle2, CircleDollarSign, Clock3, Plus, Receipt, Search, XCircle } from 'lucide-react';
import * as React from 'react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/shared/page-header';
import { useSessionUser } from '@/components/providers/session-provider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input, Textarea } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { PERMISSIONS } from '@/constants/permissions';
import { apiGet, apiPatch, apiPost, ApiRequestError } from '@/lib/api/client';
import { formatMoney } from '@/lib/money';
interface Expense{_id:string;category:string;description:string;amountMinor:number;expenseDate:string;paymentMethod:string;referenceNumber?:string;recurrence:string;status:string;requestedBy?:{name:string};approvedBy?:{name:string}} interface Resp{items:Expense[];summary:Array<{_id:string;amountMinor:number;count:number}>}
const EXPENSE_CATEGORIES = ['Rent','Electricity','Water','Gas','Internet','Staff Meals','Repairs & Maintenance','Cleaning','Delivery Charges','Marketing','Equipment','Miscellaneous'] as const;
const blank={category:'Rent',description:'',amount:'',expenseDate:new Date().toISOString().slice(0,10),paymentMethod:'cash',referenceNumber:'',recurrence:'none'};
export function ExpensesClient(){
 const user=useSessionUser(),canManage=user.permissions.includes(PERMISSIONS.EXPENSE_MANAGE),canApprove=user.permissions.includes(PERMISSIONS.EXPENSE_APPROVE);const[data,setData]=React.useState<Resp|null>(null),[search,setSearch]=React.useState(''),[open,setOpen]=React.useState(false),[form,setForm]=React.useState(blank),[saving,setSaving]=React.useState(false);
 const load=React.useCallback(async()=>setData(await apiGet<Resp>(`/api/expenses?pageSize=100${search?`&search=${encodeURIComponent(search)}`:''}`)),[search]);React.useEffect(()=>{const t=setTimeout(()=>void load(),200);return()=>clearTimeout(t)},[load]);
 async function save(){setSaving(true);try{await apiPost('/api/expenses',{...form,amountMinor:Math.round(Number(form.amount)*100),expenseDate:new Date(`${form.expenseDate}T12:00:00`),referenceNumber:form.referenceNumber||null});setOpen(false);setForm(blank);await load();toast.success('Expense submitted for approval')}catch(e){toast.error(e instanceof ApiRequestError?e.message:'Could not save expense.')}finally{setSaving(false)}}
 async function status(id:string,next:string){try{await apiPatch(`/api/expenses/${id}/status`,{status:next,rejectionReason:next==='rejected'?'Rejected during expense review':undefined});await load();toast.success(`Expense ${next}`)}catch(e){toast.error(e instanceof ApiRequestError?e.message:'Could not update status.')}}
 const sum=(s:string)=>data?.summary.find(x=>x._id===s)?.amountMinor??0,total=data?.summary.reduce((a,x)=>a+x.amountMinor,0)??0;
 return <div className="space-y-5"><PageHeader description="Operational spend, recurring costs and approval controls." actions={canManage?<Button onClick={()=>setOpen(true)}><Plus className="size-4"/>New expense</Button>:undefined}/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><M icon={CircleDollarSign} l="Total recorded" v={formatMoney(total)}/><M icon={CheckCircle2} l="Approved" v={formatMoney(sum('approved'))}/><M icon={Clock3} l="Awaiting approval" v={formatMoney(sum('pending_approval'))}/><M icon={XCircle} l="Rejected" v={formatMoney(sum('rejected'))}/></div>
  <Card><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Expense ledger</h3><p className="text-xs text-muted-foreground">Every entry keeps its requester and approval trail.</p></div><div className="relative sm:w-72"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search description or reference"/></div></div><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/45 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">Expense</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Review</th></tr></thead><tbody>{data?.items.map(e=><tr key={e._id} className="border-t hover:bg-muted/25"><td className="px-4 py-3"><p className="font-medium">{e.description}</p><p className="text-xs text-muted-foreground">{e.category}{e.referenceNumber?` · ${e.referenceNumber}`:''}</p></td><td className="px-4 py-3">{new Date(e.expenseDate).toLocaleDateString()}<span className="block text-xs text-muted-foreground">by {e.requestedBy?.name??'Staff'}</span></td><td className="px-4 py-3 capitalize">{e.paymentMethod.replace('_',' ')}</td><td className="px-4 py-3 font-semibold tabular-nums">{formatMoney(e.amountMinor)}</td><td className="px-4 py-3"><Badge variant={e.status==='approved'?'success':e.status==='rejected'?'destructive':'warning'}>{e.status.replace('_',' ')}</Badge></td><td className="px-4 py-3 text-right">{canApprove&&e.status==='pending_approval'&&<div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={()=>void status(e._id,'rejected')}>Reject</Button><Button size="sm" onClick={()=>void status(e._id,'approved')}>Approve</Button></div>}</td></tr>)}</tbody></table></div></CardContent></Card>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Record an expense</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><F l="Category"><Select value={form.category} onValueChange={v=>setForm({...form,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{EXPENSE_CATEGORIES.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></F><F l="Amount"><Input type="number" min="0" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></F><F l="Expense date"><Input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></F><F l="Payment method"><Select value={form.paymentMethod} onValueChange={v=>setForm({...form,paymentMethod:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="card">Card</SelectItem><SelectItem value="bank_transfer">Bank transfer</SelectItem><SelectItem value="digital_wallet">Digital wallet</SelectItem></SelectContent></Select></F><div className="sm:col-span-2"><F l="Description"><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></F></div><F l="Reference"><Input value={form.referenceNumber} onChange={e=>setForm({...form,referenceNumber:e.target.value})}/></F><F l="Recurrence"><Select value={form.recurrence} onValueChange={v=>setForm({...form,recurrence:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">One-time</SelectItem><SelectItem value="daily">Daily</SelectItem><SelectItem value="weekly">Weekly</SelectItem><SelectItem value="monthly">Monthly</SelectItem><SelectItem value="yearly">Yearly</SelectItem></SelectContent></Select></F></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={saving} disabled={!form.description||!Number(form.amount)} onClick={()=>void save()}>Submit expense</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
function M({icon:Icon,l,v}:{icon:typeof Receipt;l:string;v:string}){return <Card><CardContent className="flex items-center justify-between p-4"><div><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-xl font-semibold">{v}</p></div><Icon className="size-5 text-primary"/></CardContent></Card>}function F({l,children}:{l:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{l}</Label>{children}</div>}
