'use client';
import { CalendarPlus, Clock3, Coffee, UserCheck } from 'lucide-react';
import * as React from 'react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/shared/page-header';
import { useSessionUser } from '@/components/providers/session-provider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input, Textarea } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { PERMISSIONS } from '@/constants/permissions';
import { apiGet, apiPost, ApiRequestError } from '@/lib/api/client';
interface Employee{_id:string;name:string;employeeCode:string;jobTitle:string} interface RecordRow{_id:string;date:string;status:string;checkInAt?:string;checkOutAt?:string;breakMinutes:number;hoursWorked:number;employeeId:Employee} interface ShiftRow{_id:string;date:string;startTime:string;endTime:string;entryType:string;station?:string;leaveStatus?:string;employeeId:Employee} interface Data{records:RecordRow[];employees:Employee[];shifts:ShiftRow[]}
export function AttendanceClient(){
 const user=useSessionUser(),canManage=user.permissions.includes(PERMISSIONS.ATTENDANCE_MANAGE);const[data,setData]=React.useState<Data|null>(null),[mode,setMode]=React.useState<'attendance'|'shift'|null>(null),[saving,setSaving]=React.useState(false);const today=new Date().toISOString().slice(0,10);const[form,setForm]=React.useState({employeeId:'',date:today,checkIn:'09:00',checkOut:'17:00',breakMinutes:'30',status:'present',station:'Main floor',notes:''});
 const load=React.useCallback(async()=>setData(await apiGet<Data>('/api/attendance')),[]);React.useEffect(()=>{void load()},[load]);
 async function save(){setSaving(true);try{const base=new Date(`${form.date}T00:00:00`);if(mode==='attendance')await apiPost('/api/attendance',{employeeId:form.employeeId,date:base,checkInAt:new Date(`${form.date}T${form.checkIn}:00`),checkOutAt:new Date(`${form.date}T${form.checkOut}:00`),breakMinutes:Number(form.breakMinutes),status:form.status,notes:form.notes||null});else await apiPost('/api/shifts',{employeeId:form.employeeId,entryType:'shift',date:base,startTime:form.checkIn,endTime:form.checkOut,station:form.station,shiftStatus:'scheduled',notes:form.notes||null});setMode(null);await load();toast.success(mode==='attendance'?'Attendance saved':'Shift scheduled')}catch(e){toast.error(e instanceof ApiRequestError?e.message:'Could not save record.')}finally{setSaving(false)}}
 const todays=data?.records.filter(r=>r.date.slice(0,10)===today)??[],avg=todays.length?todays.reduce((s,r)=>s+r.hoursWorked,0)/todays.length:0;
 return <div className="space-y-5"><PageHeader description="Daily time records, breaks and upcoming shift coverage." actions={canManage?<><Button variant="outline" onClick={()=>setMode('attendance')}><UserCheck className="size-4"/>Record attendance</Button><Button onClick={()=>setMode('shift')}><CalendarPlus className="size-4"/>Schedule shift</Button></>:undefined}/>
  <div className="grid gap-3 sm:grid-cols-3"><M icon={UserCheck} l="Present today" v={String(todays.filter(r=>r.status==='present').length)}/><M icon={Clock3} l="Average hours" v={`${avg.toFixed(1)} h`}/><M icon={Coffee} l="Break minutes" v={String(todays.reduce((s,r)=>s+r.breakMinutes,0))}/></div>
  <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>Attendance log</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/45 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Time</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{data?.records.slice(0,20).map(r=><tr className="border-t" key={r._id}><td className="px-4 py-3 font-medium">{r.employeeId?.name??'Unknown'}<span className="block text-xs font-normal text-muted-foreground">{r.employeeId?.employeeCode}</span></td><td className="px-4 py-3">{new Date(r.date).toLocaleDateString()}</td><td className="px-4 py-3 text-muted-foreground">{r.checkInAt?new Date(r.checkInAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'} – {r.checkOutAt?new Date(r.checkOutAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Open'}</td><td className="px-4 py-3 font-medium">{r.hoursWorked.toFixed(1)}</td><td className="px-4 py-3"><Badge variant={r.status==='present'?'success':r.status==='late'?'warning':'muted'}>{r.status.replace('_',' ')}</Badge></td></tr>)}</tbody></table></div></CardContent></Card>
  <Card><CardHeader><CardTitle>Upcoming shifts</CardTitle></CardHeader><CardContent className="space-y-2">{data?.shifts.slice(0,12).map(s=><div key={s._id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium">{s.employeeId?.name}</p><p className="text-xs text-muted-foreground">{new Date(s.date).toLocaleDateString()} · {s.startTime}–{s.endTime}</p></div><Badge variant={s.entryType==='leave'?'warning':'outline'}>{s.entryType==='leave'?s.leaveStatus:'shift'}</Badge></div>{s.station&&<p className="mt-2 text-xs text-muted-foreground">{s.station}</p>}</div>)}</CardContent></Card></div>
  <Dialog open={mode!==null} onOpenChange={o=>!o&&setMode(null)}><DialogContent><DialogHeader><DialogTitle>{mode==='attendance'?'Record attendance':'Schedule shift'}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><F l="Employee"><Select value={form.employeeId} onValueChange={v=>setForm({...form,employeeId:v})}><SelectTrigger><SelectValue placeholder="Choose employee"/></SelectTrigger><SelectContent>{data?.employees.map(e=><SelectItem key={e._id} value={e._id}>{e.name}</SelectItem>)}</SelectContent></Select></F><F l="Date"><Input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></F><F l="Start / check in"><Input type="time" value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></F><F l="End / check out"><Input type="time" value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></F>{mode==='attendance'?<><F l="Break minutes"><Input type="number" value={form.breakMinutes} onChange={e=>setForm({...form,breakMinutes:e.target.value})}/></F><F l="Status"><Select value={form.status} onValueChange={v=>setForm({...form,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="present">Present</SelectItem><SelectItem value="late">Late</SelectItem><SelectItem value="absent">Absent</SelectItem><SelectItem value="on_leave">On leave</SelectItem></SelectContent></Select></F></>:<div className="sm:col-span-2"><F l="Station"><Input value={form.station} onChange={e=>setForm({...form,station:e.target.value})}/></F></div>}<div className="sm:col-span-2"><F l="Notes"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F></div></div><DialogFooter><Button variant="outline" onClick={()=>setMode(null)}>Cancel</Button><Button loading={saving} disabled={!form.employeeId} onClick={()=>void save()}>Save</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
function M({icon:Icon,l,v}:{icon:typeof Clock3;l:string;v:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><Icon className="size-5 text-primary"/><div><p className="text-xs text-muted-foreground">{l}</p><p className="text-xl font-semibold">{v}</p></div></CardContent></Card>}function F({l,children}:{l:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{l}</Label>{children}</div>}
