import { ArrowRight, BarChart3, Boxes, ChefHat, Check, Github, LayoutDashboard, ShieldCheck, ShoppingCart, Sparkles, UtensilsCrossed } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

const features=[
  {icon:ShoppingCart,title:'Lightning-fast POS',text:'Modifiers, split payments, held orders, table service and polished receipts.'},
  {icon:ChefHat,title:'Live kitchen display',text:'Station filters, preparation timers, priority warnings and real-time ticket flow.'},
  {icon:Boxes,title:'Recipe-level inventory',text:'Stock movements, purchase receiving, wastage, counts and automatic deductions.'},
  {icon:BarChart3,title:'Actionable reporting',text:'Sales, profit, payment, product and operational reporting with export.'},
  {icon:ShieldCheck,title:'Role-secure operations',text:'Seven restaurant roles with granular permissions and branch-level data scope.'},
  {icon:UtensilsCrossed,title:'Complete restaurant suite',text:'Tables, bookings, delivery, CRM, loyalty, workforce, expenses and settings.'},
];
export default function LandingPage(){return <main className="min-h-screen bg-[#071923] text-white">
 <nav className="sticky top-0 z-40 border-b border-white/10 bg-[#071923]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-teal-400 text-[#06201e]"><UtensilsCrossed className="size-5"/></span><span className="font-display text-lg font-semibold">DineFlow <span className="text-teal-300">POS</span></span></Link><div className="flex items-center gap-2"><Button asChild variant="ghost" className="text-slate-300 hover:bg-white/10 hover:text-white"><Link href="#features">Features</Link></Button><Button asChild className="bg-teal-400 text-[#06201e] hover:bg-teal-300"><Link href="/login">Open demo <ArrowRight className="size-4"/></Link></Button></div></div></nav>
 <section className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_15%,rgba(23,162,155,.2),transparent_35%),radial-gradient(circle_at_10%_60%,rgba(42,120,214,.14),transparent_30%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-teal-300/25 bg-teal-300/10 px-3 py-1.5 text-xs font-medium text-teal-200"><Sparkles className="size-3.5"/>Commercial restaurant operations, unified</div><h1 className="mt-6 font-display text-5xl leading-[1.05] font-semibold tracking-tight sm:text-6xl">Serve faster.<br/><span className="text-teal-300">Run smarter.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">A production-style restaurant management and point-of-sale platform built for dining rooms, kitchens, inventory teams and multi-branch operators.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-teal-400 text-[#06201e] hover:bg-teal-300"><Link href="/login">Explore live demo <ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10"><a href="https://github.com/" target="_blank" rel="noreferrer"><Github className="size-4"/>GitHub</a></Button></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-400">{['No paid services','Seven demo roles','Responsive UI','Dark mode'].map(x=><span className="flex items-center gap-1.5" key={x}><Check className="size-3.5 text-teal-300"/>{x}</span>)}</div></div>
 <div className="rounded-2xl border border-white/10 bg-white/[.06] p-3 shadow-2xl shadow-black/30 backdrop-blur"><div className="rounded-xl bg-[#f4f7f8] p-4 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-500">Monday overview</p><p className="text-lg font-semibold">Good evening, Manager</p></div><span className="rounded-lg bg-teal-50 px-3 py-1.5 text-xs font-medium text-teal-700">Colombo Central</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Sales','$12,840'],['Orders','186'],['Avg. order','$69.03'],['Net profit','$8,240']].map(([l,v])=><div className="rounded-xl border bg-white p-3" key={l}><p className="text-[10px] text-slate-500">{l}</p><p className="mt-1 text-lg font-semibold">{v}</p></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-[1.4fr_.6fr]"><div className="rounded-xl border bg-white p-4"><div className="flex h-40 items-end gap-2">{[32,48,38,65,54,82,74,91,70,88,96,78].map((h,i)=><div key={i} style={{height:`${h}%`}} className="flex-1 rounded-t bg-teal-500/80"/>)}</div></div><div className="space-y-2">{[['Kitchen queue','8 tickets'],['Tables active','14 / 20'],['Low stock','6 items']].map(([a,b])=><div className="rounded-xl border bg-white p-3" key={a}><p className="text-[10px] text-slate-500">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</div></div></div></div></div></section>
 <section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-5 py-8 text-center sm:grid-cols-4">{[['60+','Menu items'],['50+','Historical orders'],['21','Core modules'],['3','Demo branches']].map(([v,l])=><div key={l}><p className="text-2xl font-semibold text-teal-300">{v}</p><p className="mt-1 text-xs text-slate-400">{l}</p></div>)}</div></section>
 <section id="features" className="mx-auto max-w-7xl px-5 py-20"><div className="max-w-2xl"><p className="text-sm font-semibold text-teal-300">ONE OPERATING SYSTEM</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Everything your restaurant team needs</h2><p className="mt-4 text-slate-400">Connected workflows replace scattered tools and give each role exactly the controls they need.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-white/10 bg-white/[.04] p-6 transition hover:-translate-y-1 hover:border-teal-300/30"><div className="grid size-11 place-items-center rounded-xl bg-teal-300/10 text-teal-300"><Icon className="size-5"/></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></section>
 <section className="mx-auto max-w-7xl px-5 pb-20"><div className="overflow-hidden rounded-3xl bg-gradient-to-br from-teal-400 to-cyan-300 p-8 text-[#06201e] sm:p-12"><div className="grid gap-6 sm:grid-cols-[1fr_auto] sm:items-center"><div><LayoutDashboard className="size-8"/><h2 className="mt-4 font-display text-3xl font-semibold">Experience the complete workflow</h2><p className="mt-2 max-w-2xl text-sm text-[#0a4a47]">Use the safely displayed demo credentials to review the dashboard, POS, kitchen, inventory and administration experiences.</p></div><Button asChild size="lg" className="bg-[#071923] text-white hover:bg-[#0c2b39]"><Link href="/login">Launch DineFlow <ArrowRight className="size-4"/></Link></Button></div></div></section>
 <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 DineFlow POS. Portfolio demonstration project.</p><p>Next.js · TypeScript · MongoDB · Tailwind CSS</p></div></footer>
 </main>}
