'use client';
import { Briefcase, Plus, Search, UserCheck, Users } from 'lucide-react';
import * as React from 'react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/shared/page-header';
import { useSessionUser } from '@/components/providers/session-provider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { SkeletonTable } from '@/components/ui/skeleton';
import { PERMISSIONS } from '@/constants/permissions';
import { apiGet, apiPatch, apiPost, ApiRequestError } from '@/lib/api/client';
import { formatMoney } from '@/lib/money';

interface Employee {_id:string;name:string;employeeCode:string;jobTitle:string;department:string;phone:string;email?:string;hireDate:string;employmentType:string;employmentStatus:string;salaryType:string;monthlySalaryMinor?:number;hourlyRateMinor?:number}
const blank={name:'',employeeCode:'',jobTitle:'',department:'Operations',phone:'',email:'',hireDate:new Date().toISOString().slice(0,10),employmentType:'full_time',employmentStatus:'active',salaryType:'monthly',monthlySalary:'',hourlyRate:''};
export function EmployeesClient(){
 const user=useSessionUser(), canManage=user.permissions.includes(PERMISSIONS.EMPLOYEE_MANAGE), canSalary=user.permissions.includes(PERMISSIONS.EMPLOYEE_VIEW_SALARY);
 const [items,setItems]=React.useState<Employee[]|null>(null),[search,setSearch]=React.useState(''),[open,setOpen]=React.useState(false),[editing,setEditing]=React.useState<Employee|null>(null),[form,setForm]=React.useState(blank),[saving,setSaving]=React.useState(false);
 const load=React.useCallback(async()=>setItems(await apiGet<Employee[]>(`/api/employees?pageSize=100${search?`&search=${encodeURIComponent(search)}`:''}`)),[search]);
 React.useEffect(()=>{const t=setTimeout(()=>void load(),200);return()=>clearTimeout(t)},[load]);
 function edit(e?:Employee){setEditing(e??null);setForm(e?{name:e.name,employeeCode:e.employeeCode,jobTitle:e.jobTitle,department:e.department,phone:e.phone,email:e.email??'',hireDate:e.hireDate.slice(0,10),employmentType:e.employmentType,employmentStatus:e.employmentStatus,salaryType:e.salaryType,monthlySalary:e.monthlySalaryMinor!==undefined?String(e.monthlySalaryMinor/100):'',hourlyRate:e.hourlyRateMinor!==undefined?String(e.hourlyRateMinor/100):''}:blank);setOpen(true)}
 async function save(){setSaving(true);try{const {monthlySalary,hourlyRate,...publicFields}=form;const body=canSalary?{...publicFields,monthlySalaryMinor:Math.round(Number(monthlySalary||0)*100),hourlyRateMinor:Math.round(Number(hourlyRate||0)*100)}:publicFields;if(editing)await apiPatch(`/api/employees/${editing._id}`,body);else await apiPost('/api/employees',body);setOpen(false);await load();toast.success(editing?'Employee updated':'Employee added')}catch(e){toast.error(e instanceof ApiRequestError?e.message:'Could not save employee.')}finally{setSaving(false)}}
 const active=items?.filter(i=>i.employmentStatus==='active').length??0, departments=new Set(items?.map(i=>i.department)).size;
 return <div className="space-y-5"><PageHeader description="Team profiles, roles, employment status and compensation controls." actions={canManage?<Button onClick={()=>edit()}><Plus className="size-4"/>Add employee</Button>:undefined}/>
  <div className="grid gap-3 sm:grid-cols-3"><Metric icon={Users} label="Team members" value={String(items?.length??'—')}/><Metric icon={UserCheck} label="Active today" value={String(active)}/><Metric icon={Briefcase} label="Departments" value={String(departments)}/></div>
  <Card><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Employee directory</h3><p className="text-xs text-muted-foreground">Salary fields only appear for authorised roles.</p></div><div className="relative sm:w-72"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search team members"/></div></div><CardContent className="p-0">{!items?<div className="p-5"><SkeletonTable rows={7} columns={6}/></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/45 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th>{canSalary&&<th className="px-4 py-3">Compensation</th>}<th className="px-4 py-3">Joined</th></tr></thead><tbody>{items.map(e=><tr key={e._id} className="border-t hover:bg-muted/25"><td className="px-4 py-3"><button className="text-left" onClick={()=>canManage&&edit(e)}><span className="font-medium">{e.name}</span><span className="block text-xs text-muted-foreground">{e.employeeCode} · {e.phone}</span></button></td><td className="px-4 py-3">{e.jobTitle}<span className="block text-xs text-muted-foreground">{e.department}</span></td><td className="px-4 py-3 capitalize">{e.employmentType.replace('_',' ')}</td><td className="px-4 py-3"><Badge variant={e.employmentStatus==='active'?'success':e.employmentStatus==='on_leave'?'warning':'muted'}>{e.employmentStatus.replace('_',' ')}</Badge></td>{canSalary&&<td className="px-4 py-3 font-medium">{e.salaryType==='monthly'?formatMoney(e.monthlySalaryMinor??0):`${formatMoney(e.hourlyRateMinor??0)}/hr`}</td>}<td className="px-4 py-3 text-muted-foreground">{new Date(e.hireDate).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</CardContent></Card>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent size="lg"><DialogHeader><DialogTitle>{editing?'Edit employee':'Add employee'}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><F l="Full name"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></F><F l="Employee code"><Input value={form.employeeCode} onChange={e=>setForm({...form,employeeCode:e.target.value})}/></F><F l="Job title"><Input value={form.jobTitle} onChange={e=>setForm({...form,jobTitle:e.target.value})}/></F><F l="Department"><Input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></F><F l="Phone"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></F><F l="Email"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></F><F l="Hire date"><Input type="date" value={form.hireDate} onChange={e=>setForm({...form,hireDate:e.target.value})}/></F><F l="Employment type"><Select value={form.employmentType} onValueChange={v=>setForm({...form,employmentType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="full_time">Full time</SelectItem><SelectItem value="part_time">Part time</SelectItem><SelectItem value="contract">Contract</SelectItem><SelectItem value="casual">Casual</SelectItem></SelectContent></Select></F>{canSalary&&<><F l="Salary basis"><Select value={form.salaryType} onValueChange={v=>setForm({...form,salaryType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="monthly">Monthly</SelectItem><SelectItem value="hourly">Hourly</SelectItem></SelectContent></Select></F><F l={form.salaryType==='monthly'?'Monthly salary':'Hourly rate'}><Input type="number" value={form.salaryType==='monthly'?form.monthlySalary:form.hourlyRate} onChange={e=>setForm({...form,[form.salaryType==='monthly'?'monthlySalary':'hourlyRate']:e.target.value})}/></F></>}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={saving} disabled={!form.name||!form.employeeCode||!form.jobTitle||!form.phone} onClick={()=>void save()}>Save employee</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-primary/10 p-2.5 text-primary"><Icon className="size-5"/></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></div></CardContent></Card>}
function F({l,children}:{l:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{l}</Label>{children}</div>}
